name: Build Web

on:
  push:
    branches: ["master", "web-prod"]
  pull_request:
    branches: ["master"]
  merge_group:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
      - name: Retrieve version after install
        id: nodenv
        run: echo "node-version=$(node -v | sed 's/^v//')" >> $GITHUB_OUTPUT
      - uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: web
          containerfiles: |
            Dockerfile
          build-args: |
            NODE_VERSION=${{ steps.nodenv.outputs.node-version }}-slim
          extra-args: |
            --ulimit nofile=65536:65536
